# Generated by Django 5.1.6 on 2025-03-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_profile/avatar_blank.jpg', upload_to='profile_pictures/'),
        ),
    ]
