# Generated by Django 5.2 on 2025-05-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditapp', '0003_pendinguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
